[package]
name = "mt-symetric"
version.workspace = true
edition.workspace = true

[dependencies]
koala-bear = { path = "../koala-bear", package = "mt-koala-bear" }
field = { path = "../field", package = "mt-field" }
blake3 = "1"
rayon.workspace = true
