[package]
name = "xmss"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]

rand.workspace = true
utils.workspace = true
multilinear-toolkit.workspace = true
sha3.workspace = true