[package]
name = "xmss"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
p3-koala-bear.workspace = true
p3-symmetric.workspace = true
rand.workspace = true
utils.workspace = true
multilinear-toolkit.workspace = true
sha3.workspace = true