[package]
name = "xmss"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]

rand.workspace = true
utils.workspace = true
backend.workspace = true
serde.workspace = true