[package]
name = "utils"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]

tracing-forest.workspace = true


tracing-subscriber.workspace = true
tracing.workspace = true

backend.workspace = true

[dev-dependencies]
rand.workspace = true
